### PR TITLE
Fix Issue #15: Cache bucket/key in riak_operation

### PR DESCRIPTION
**Pull request by hazen**
Since these fields are not returned in the request, the only way to return them in the riak_object is to cache them in the GET request.

### CODE REVIEW

**Comment by hazen** [comment]
Maybe I should have pull develop? Not sure the best way to get all of the pending changes we already merged.  Guess I could try that, too.

**Comment by bookshelfdave** [comment]
Are there other things we'll eventually need to cache in the operation? Or, could this be made more general to support other values?

**Comment by hazen** [comment]
Great question.  On the other hand, bucket and key are pretty darned fundamental to Riak.  I can pose the question to the client boys tomorrow to see what everyone else is caching.

**Comment by hazen** [comment]
@metadave Just asked in the Eng:Clients room and Java at least only caches the bucket and key FWIW

**Comment by bookshelfdave** [comment]
+1

**Pull request merged**
