### PR TITLE
Add Integration Tests for Map/Reduce

### PR DESCRIPTION
**Pull request by hazen**
- Tweak a few test generators to restrict test strings to [0-9A-Za-z] to make Javascript happy
- Add some missing interfaces
- Clean up a memory leak

### CODE REVIEW

**Comment by bookshelfdave** [comment]
@javajolt the test failed twice for me, then passed on the third try:

https://gist.github.com/metadave/9739118

**Comment by hazen** [comment]
Crap.  OK.  It's the async streaming.  I guess I should turn it off for that test otherwise I'll never be able to actually predict which parts of the message will be coming back at any one time.  Or I guess I could try to figure out how to track the state over different messages...

**Comment by bookshelfdave** [comment]
multiple test runs pass, 
+1

**Comment by hazen** [comment]
Yippee! :fireworks:

**Pull request merged**
